[package]
name = "rlbot"
version.workspace = true
edition = "2024"
rust-version.workspace = true
description = "Rust bindings for the RLBot framework, allowing you to write bots for Rocket League in Rust."
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["bot", "rlbot", "rocket-league"]
categories = ["api-bindings", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kanal = { version = "0.1.1", default-features = false }
mio = { version = "1.1.0", features = ["net", "os-poll"] }
rlbot_flat = { path = "../rlbot_flat", version = "0.6.0" }
thiserror = "2.0.12"

[features]
default = ["glam"]
glam = ["rlbot_flat/glam"]

[lints.clippy]
all = "warn"
