[workspace]
package.version = "0.6.0"
package.rust-version = "1.88"
package.homepage = "https://rlbot.org"
package.repository = "https://github.com/RLBot/rust-interface"
package.license = "MIT"
resolver = "3"
members = ["rlbot", "rlbot_flat"]

[profile.dev]
opt-level = 3
panic = "abort"
codegen-units = 1

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
codegen-units = 1
