[package]
name = "rlbot-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "24.3.25"
glam = { version = "0.27.0", optional = true }
thiserror = "1.0.50"

[features]
default = ["glam"]
glam = ["dep:glam"]

[build-dependencies]
regex = "1.10.3"
