[package]
name = "rlbot-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.13"
glam = { version = "0.27.0", optional = true }
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.50"
planus = "0.4.0"

[features]
default = ["glam"]
glam = ["dep:glam"]

[build-dependencies]
planus-translation = "0.4.0"
planus-codegen = "0.4.0"
