[package]
name = "rlbot-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.13"
flatbuffers = { version = "24.3.25", features = ["serialize"] }
glam = { version = "0.27.0", optional = true }
planus = "0.4.0"
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.50"

[features]
default = ["glam"]
glam = ["dep:glam"]

[build-dependencies]
regex = "1.10.3"
