[package]
name = "rlbot-interface"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.13"
glam = { version = "0.27.0", optional = true }
serde = { version = "1.0.210", features = ["derive"] }
thiserror = "1.0.50"
planus = { "git" = "https://github.com/swz-git/planus", rev = "b35f9df" }

[features]
default = ["glam"]
glam = ["dep:glam"]

[build-dependencies]
planus-translation = { "git" = "https://github.com/swz-git/planus", rev = "b35f9df" }
planus-codegen = { "git" = "https://github.com/swz-git/planus", rev = "b35f9df" }
