[package]
name = "rlbot-interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = { git = "https://github.com/google/flatbuffers", rev = "129ef422" }
glam = { version = "0.25.0", optional = true }
thiserror = "1.0.50"

[features]
default = ["glam"]
glam = ["dep:glam"]

[build-dependencies]
regex = "1.10.3"
