[settings]
name = "High Jump Script"
agent_id = "rlbot/rust-example/high_jump_script"
run_command = "..\\..\\..\\..\\target\\release\\examples\\high_jump_script.exe"
run_command_linux = "../../../../target/release/examples/high_jump_script"

[details]
# description = ""
# fun_fact = ""
# source_link = "https://github.com/RLBot/rust-interface"
developer = ""
language = "rust"
# logo_file = "logo.png"
